version: "3.1"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - mongo-compose-network
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb

  api:
    build: .
    environment:
      PORT: 3500
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/
      DB_NAME: demo_db
      DB_USER: admin
      DB_PASS: admin
      NODE_ENV: development
    ports:
      - 3500:3500
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb: {}
